version: '3.4'

services:
  beersales.api:
    image: ${DOCKER_REGISTRY-}beersalesapi
    build:
      context: .
      dockerfile: BeerSales.Api/Dockerfile
      
  beersales.db:
    image: mcr.microsoft.com/mssql/server:2019-latest 